apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  selector:
    app: mi-app
  ports:
  - protocol: TCP
    port: 80      # Puerto accesible dentro del clúster
    targetPort: 8080 # Puerto del contenedor (debe coincidir con containerPort en `deployment.yaml`)
  type: NodePort   # Permite acceder a la aplicación desde fuera de Minikube
