name: CI/CD para mi-app

on:
  push:
    branches:
      - main  # Ejecuta este flujo de trabajo cada vez que se haga un 'push' a la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v2
    
    - name: Configurar Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
    
    - name: Construir la imagen Docker
      run: |
        docker build -t miusuario/mi-app:latest .
    
    - name: Subir la imagen Docker a Docker Hub
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push miusuario/mi-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Configurar kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Desplegar en Kubernetes
      run: |
        kubectl apply -f deployment.yaml
